### ISSUE TITLE
Problems occured when trainning on custom data

### ISSUE THREAD

**Issue by xjchao7** [jby1993/SelfReconCode#13]
Hi!
Thank you for your job.

I met problem when I run train.py on our own data. The problem is shown as follows:
![problem](https://user-images.githubusercontent.com/105781839/177154558-2150aa2e-3c27-4f34-adfe-969e3b011d94.png)

I have checked that the file format is the same. Do you know what the problem might be? The images I used were 2160*3840 segmented images.

**Comment by jby1993** [comment]
I did not test such large resolution images. It looks like the bin_size is None, it should be a bug.

**Comment by Xianjin111** [comment]
> I did not test such large resolution images. It looks like the bin_size is None, it should be a bug.

Thank you for your reply. When I utilize the 1080p, the problem will not occurred.

**Comment by zhan-xu** [comment]
@Xianjin111 @xjchao7 Hi, I am also trying to use my own video sequences. Did you use videoavatars to get "reconstructed_poses.hdf5" first? In this case, how did you first get "keypoints.hdf5" and "camera.pkl"? I assume I can get masks using detectron2 or something... Any help would be very appreciated. Thank you!

**Comment by Xianjin111** [comment]
> @Xianjin111 @xjchao7 Hi, I am also trying to use my own video sequences. Did you use videoavatars to get "reconstructed_poses.hdf5" first? In this case, how did you first get "keypoints.hdf5" and "camera.pkl"? I assume I can get masks using detectron2 or something... Any help would be very appreciated. Thank you!

Hi, you could use the scripts in Videoavatar/preparedata to get both of them.

**Comment by zhan-xu** [comment]
@Xianjin111 Thanks for your answer!

**Comment by zhan-xu** [comment]
Hi @Xianjin111 @jby1993, sorry I have another question.
[Here](https://github.com/jby1993/SelfReconCode/blob/main/people_snapshot_process.py#L55), the author changes (1080, 1920) to (1920, 1080). Does the video have to be portrait orientation? Can I train with landscape orientation video? (because when rotate, human won't keep head up) 

Also, is there an alternative method to fit smpl model and output one global beta for the whole video? A quick try of videoavatar doesn't work well on my customized video, and it is very very slow. Most SMPL fitting methods are image based, meaning that they output different beta for different frame. Simple averaging beta from all frames didn't work well.

**Comment by Xianjin111** [comment]
> [Here](https://github.com/jby1993/SelfReconCode/blob/main/people_snapshot_process.py#L55), the author changes (1080, 1920) to (1920, 1080). Does the video have to be portrait orientation? Can I train with landscape orientation video? (because when rotate, human won't keep head up)

I have the same problem. @jby1993

**Comment by jby1993** [comment]
Nothing about portrait or landscape orientation. Make sure the camera parameters are correct. Why I transformed the images should be to make the camera intrinsic match for some data, but I also forget the details.

**Comment by vastskymiaow** [comment]
Is there any tool to create masks of a video? masks2hdf5.py in videoavatar/prepare_data takes masks (png) as a input.
