### ISSUE TITLE
How to run code in zju_mocap dataset?

### ISSUE THREAD

**Issue by Yzmblog** [jby1993/SelfReconCode#18]
Hi, Thanks for your great work! And I saw you have run self_recon in zju_mocap in your project page, I want to ask that how to do this? Is it directly trained by the motion sequence of the data?

**Comment by jby1993** [comment]
You need to convert the current codes to support multi-view inputs and write a dataset to read the easymocap's initial smpl and camera parameters.

**Comment by gqbay** [comment]
> You need to convert the current codes to support multi-view inputs and write a dataset to read the easymocap's initial smpl and camera parameters.

Using this opportunity, I am so curious: if I have easymocap animation with SMPL mesh, can SelfRecon change SMPL mesh that the shape of the mesh will matching with the human on the video? 

Now I have result like in attached video. But I want the shape matching like on your amazing examples. 

Thanks in advance! 🙏

P.S: the only reason shapes matching on the video is because I did some cheating with sculpting and manual keyframe animation that looks okay from camera perspective, but looks weird from different  angles 😢

https://user-images.githubusercontent.com/65506709/179741944-61ff6aed-9729-4a33-a008-80841cf23f60.MOV

**Comment by jby1993** [comment]
Multi-view inputs under a controlled environment are required to generate satisfying results for general motions. For a wild video with so few views, I doubt the quality of reconstruction.

**Comment by gqbay** [comment]
> Multi-view inputs under a controlled environment are required to generate satisfying results for general motions. For a wild video with so few views, I doubt the quality of reconstruction.

I mean, I could use up to 4 views. Is it enough?

**Comment by jby1993** [comment]
The multiview inputs for general motions are not supported in current repo, because it's not stable

**Comment by Yzmblog** [comment]
> The multiview inputs for general motions are not supported in current repo, because it's not stable

Hi, Thanks for your quick reply!  And I want to ask that can SelfRecon train in some complex motion sequence monocular data(not just A-pose)? Because I when i try SelfRecon in some youtube dance video, It seems that the reconstruction result is kind of bad.

**Comment by jby1993** [comment]
I think it cannot be use in this case directly.

**Comment by Yzmblog** [comment]
> I think it cannot be use in this case directly.

Got it, thanks again!
